# Generated by Django 4.2.2 on 2023-08-26 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuerza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fuerza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.fuerza')),
            ],
        ),
        migrations.AddField(
            model_name='fuerza',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.pais'),
        ),
    ]
