# Generated by Django 4.2.2 on 2023-08-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='abreviacion',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
