# Generated by Django 4.2.2 on 2023-08-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_pais_abreviacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuerza',
            options={'verbose_name': 'Fuerza', 'verbose_name_plural': 'Fuerzas'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='regimiento',
            options={'verbose_name': 'Regimiento', 'verbose_name_plural': 'Regimientos'},
        ),
        migrations.AlterModelTable(
            name='fuerza',
            table='fuerza',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='pais',
        ),
        migrations.AlterModelTable(
            name='regimiento',
            table='regimiento',
        ),
    ]
